filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/*.log
      - /var/log/php/*.log

output.logstash:
  hosts: ["fluentd:24224"]

# output.elasticsearch:
#   hosts: ["http://elasticsearch:9200"]
#   # username: "elastic"
#   # password: "yourpassword"
