
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Mailserver
    - name: Copy Mailserver config folder
      ansible.builtin.copy:
        src: template/mailserver/
        dest: tools/mailserver/
        owner: root
        group: root
        mode: '0644'
      poll: 1
      when: install_mailserver is true

    - name: Generate mailserver.yml from template
      ansible.builtin.template:
        src: template/mailserver.yml.j2
        dest: tools/mailserver.yml
        owner: root
        group: root
        mode: '0644'
        force: yes
      poll: 1
      when: install_mailserver is true

    - name: Set up Mailserver using Docker Compose
      community.docker.docker_compose_v2:
        project_src: tools
        files:
          - mailserver.yml
        state: present
        pull: always
        recreate: auto
      poll: 1
      when: install_mailserver is true

    - name: Check if mailserver.yml file exists
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/tools/mailserver.yml"
      register: mailserver_file
      poll: 1

    - name: Tear down Mailserver container if install_mailserver is false
      community.docker.docker_compose_v2:
        project_src: tools
        files:
          - mailserver.yml
        state: absent
      poll: 1
      when: install_mailserver is false and mailserver_file.stat.exists
