auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2025-08-01   # تاریخ شروع نسخه جدید
      store: tsdb         # تغییر داده شد
      object_store: filesystem
      schema: v13         # ارتقاء داده شد
      index:
        prefix: index_
        period: 24h

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_query_lookback: 168h
  # این خط رو دوباره فعال نکن مگر بعد از مهاجرت کامل
  # allow_structured_metadata: true

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
